import Foundation

class DeveloperPreview{
    var listings: [Listing] = [
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "John Smith",
            ownerImageUrl: "profile 1",
            numberOfBedrooms: 4,
            numberOfBathrooms: 3,
            numberOfGuests: 3,
            numberOfBeds: 4,
            pricePerNight: 567,
            latitude: 25.7850,
            longitude: -80.1936,
            imageUrls: ["listing 1", "listing 3", "listing 4", "listing 2"],
            address: "124 Main Street",
            city: "Miami",
            state: "Florida",
            title: "Miami Villa",
            rating: 4.86,
            features: [.selfCheckIn, .superHost],
            amenities: [.wifi, .alarmSystem, .balcony, .tv, .laundry],
            type: .villa
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Paul Aaron",
            ownerImageUrl: "profile 1",
            numberOfBedrooms: 4,
            numberOfBathrooms: 4,
            numberOfGuests: 2,
            numberOfBeds: 4,
            pricePerNight: 763,
            latitude: 25.7706,
            longitude: -80.1340,
            imageUrls: ["listing 3", "listing 2", "listing 1", "listing 4"],
            address: "124 Main Street",
            city: "Miami",
            state: "Florida",
            title: "Miami Beach House",
            rating: 4.51,
            features: [.selfCheckIn, .superHost],
            amenities: [.wifi, .alarmSystem, .tv, .kitchen, .office],
            type: .house
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Steve Johnson",
            ownerImageUrl: "profile 1",
            numberOfBedrooms: 4,
            numberOfBathrooms: 3,
            numberOfGuests: 2,
            numberOfBeds: 4,
            pricePerNight: 700,
            latitude: 25.7650,
            longitude: -80.1936,
            imageUrls: ["listing 1", "listing 2", "listing 4", "listing 2"],
            address: "124 Main Street",
            city: "Miami",
            state: "Florida",
            title: "Beautiful Miami apartment in Brickell",
            rating: 4.32,
            features: [.selfCheckIn, .superHost],
            amenities: [.wifi, .alarmSystem, .balcony],
            type: .apartment
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Harold",
            ownerImageUrl: "profile 1",
            numberOfBedrooms: 4,
            numberOfBathrooms: 3,
            numberOfGuests: 3,
            numberOfBeds: 4,
            pricePerNight: 815,
            latitude: 34.2,
            longitude: -118.0426,
            imageUrls: ["listing 4", "listing 2", "listing 3", "listing 1"],
            address: "124 Main Street",
            city: "Los Angeles",
            state: "California",
            title: "Beautiful Los Angeles home in Malibu",
            rating: 4.97,
            features: [.selfCheckIn, .superHost],
            amenities: [.wifi, .alarmSystem, .pool],
            type: .apartment
        )
    ]
}
